### ISSUE TITLE
What is the source of the data

### ISSUE THREAD

**Issue by zelima** [datasets/population-global-historical#1]
@Mikanebu There is no URL in the readme or dp.json for the original data. Where it comes from?

**Comment by Mikanebu** [comment]
@zelima I could not find it, only source `Appendix in Joel E. Cohen, How Many People Can the Earth Support?, Norton 1996, ISBN 0-393-31495-2.`

**Comment by zelima** [comment]
@Mikanebu but this dataset is made by you, all 6 commits are yours. It should be coming from somewhere, right?

**Comment by Mikanebu** [comment]
@zelima yes, I moved here from old `econ` datasets https://github.com/okfn/econ/tree/master/econdata

**Comment by zelima** [comment]
INVALID we don't have source yet moved in #2
