### ISSUE TITLE
Better source for this dataset

### ISSUE THREAD

**Issue by zelima** [datasets/population-global-historical#2]
as discussed here #1 we don't have the source for original data. And data itself seems very old (latest data for 1990). We need a better source for this. Options

* till 2015 https://ourworldindata.org/world-population-growth/
  * in csv https://ourworldindata.org/wp-content/uploads/2013/05/WorldPopulationAnnual12000years_interpolated_HYDEandUNto2015.csv
* till 2017  (also available  male/female growth rate etc...): https://esa.un.org/unpd/wpp/Download/Standard/Population/
  * xls for total: https://esa.un.org/unpd/wpp/DVD/Files/1_Indicators%20(Standard)/EXCEL_FILES/1_Population/WPP2017_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES.xlsx
* more?

**Comment by rufuspollock** [comment]
@zelima this data is hand-copied by me from appendix in Joel Cohen's "How Many People Can the Earth Support".

NOTE: **This is is a historical dataset so it does not need updating.**

The source is stated clearly in the README 😉

**Comment by zelima** [comment]
ok so WONTFIX
